local name = 'emoji'

local source = {}

---Return whether this source is available in the current context or not (optional).
---@return boolean
function source:is_available()
  return true
end

---Return the debug name of this source (optional).
---@return string
function source:get_debug_name()
  return name
end

---Return LSP's PositionEncodingKind.
---@NOTE: If this method is ommited, the default value will be `utf-16`.
---@return lsp.PositionEncodingKind
function source:get_position_encoding_kind()
  return 'utf-16'
end

---Return the keyword pattern for triggering completion (optional).
---If this is ommited, nvim-cmp will use a default keyword pattern. See |cmp-config.completion.keyword_pattern|.
---@return string
function source:get_keyword_pattern()
  return [[\k\+]]
end

---Return trigger characters for triggering completion (optional).
function source:get_trigger_characters()
  return { '.' }
end

---Invoke completion (required).
---@param params cmp.SourceCompletionApiParams
---@param callback fun(response: lsp.CompletionResponse|nil)
function source:complete(params, callback)
  callback({
    { label = ':bowtie:' }, { label = ':smile:' }, { label = ':laughing:' },
    { label = ':blush:' }, { label = ':smiley:' }, { label = ':relaxed:' },
    { label = ':smirk:' }, { label = ':heart_eyes:' }, { label = ':kissing_heart:' },
    { label = ':kissing_closed_eyes:' }, { label = ':flushed:' }, { label = ':relieved:' },
    { label = ':satisfied:' }, { label = ':grin:' }, { label = ':wink:' },
    { label = ':stuck_out_tongue_winking_eye:' }, { label = ':stuck_out_tongue_closed_eyes:' }, { label = ':grinning:' },
    { label = ':kissing:' }, { label = ':kissing_smiling_eyes:' }, { label = ':stuck_out_tongue:' },
    { label = ':sleeping:' }, { label = ':worried:' }, { label = ':frowning:' },
    { label = ':anguished:' }, { label = ':open_mouth:' }, { label = ':grimacing:' },
    { label = ':confused:' }, { label = ':hushed:' }, { label = ':expressionless:' },
    { label = ':unamused:' }, { label = ':sweat_smile:' }, { label = ':sweat:' },
    { label = ':disappointed_relieved:' }, { label = ':weary:' }, { label = ':pensive:' },
    { label = ':disappointed:' }, { label = ':confounded:' }, { label = ':fearful:' },
    { label = ':cold_sweat:' }, { label = ':persevere:' }, { label = ':cry:' },
    { label = ':sob:' }, { label = ':joy:' }, { label = ':astonished:' },
    { label = ':scream:' }, { label = ':neckbeard:' }, { label = ':tired_face:' },
    { label = ':angry:' }, { label = ':rage:' }, { label = ':triumph:' },
    { label = ':sleepy:' }, { label = ':yum:' }, { label = ':mask:' },
    { label = ':sunglasses:' }, { label = ':dizzy_face:' }, { label = ':imp:' },
    { label = ':smiling_imp:' }, { label = ':neutral_face:' }, { label = ':no_mouth:' },
    { label = ':innocent:' }, { label = ':alien:' }, { label = ':yellow_heart:' },
    { label = ':blue_heart:' }, { label = ':purple_heart:' }, { label = ':heart:' },
    { label = ':green_heart:' }, { label = ':broken_heart:' }, { label = ':heartbeat:' },
    { label = ':heartpulse:' }, { label = ':two_hearts:' }, { label = ':revolving_hearts:' },
    { label = ':cupid:' }, { label = ':sparkling_heart:' }, { label = ':sparkles:' },
    { label = ':star:' }, { label = ':star2:' }, { label = ':dizzy:' },
    { label = ':boom:' }, { label = ':collision:' }, { label = ':anger:' },
    { label = ':exclamation:' }, { label = ':question:' }, { label = ':grey_exclamation:' },
    { label = ':grey_question:' }, { label = ':zzz:' }, { label = ':dash:' },
    { label = ':sweat_drops:' }, { label = ':notes:' }, { label = ':musical_note:' },
    { label = ':fire:' }, { label = ':hankey:' }, { label = ':poop:' },
    { label = ':shit:' }, { label = ':+1:' }, { label = ':thumbsup:' },
    { label = '-1' }, { label = ':thumbsdown:' }, { label = ':ok_hand:' },
    { label = ':punch:' }, { label = ':facepunch:' }, { label = ':fist:' },
    { label = ':v:' }, { label = ':wave:' }, { label = ':hand:' },
    { label = ':raised_hand:' }, { label = ':open_hands:' }, { label = ':point_up:' },
    { label = ':point_down:' }, { label = ':point_left:' }, { label = ':point_right:' },
    { label = ':raised_hands:' }, { label = ':pray:' }, { label = ':point_up_2:' },
    { label = ':clap:' }, { label = ':muscle:' }, { label = ':metal:' },
    { label = ':fu:' }, { label = ':walking:' }, { label = ':runner:' },
    { label = ':running:' }, { label = ':couple:' }, { label = ':family:' },
    { label = ':two_men_holding_hands:' }, { label = ':two_women_holding_hands:' }, { label = ':dancer:' },
    { label = ':dancers:' }, { label = ':ok_woman:' }, { label = ':no_good:' },
    { label = ':information_desk_person:' }, { label = ':raising_hand:' }, { label = ':bride_with_veil:' },
    { label = ':person_with_pouting_face:' }, { label = ':person_frowning:' }, { label = ':bow:' },
    { label = ':couplekiss:' }, { label = ':couple_with_heart:' }, { label = ':massage:' },
    { label = ':haircut:' }, { label = ':nail_care:' }, { label = ':boy:' },
    { label = ':girl:' }, { label = ':woman:' }, { label = ':man:' },
    { label = ':baby:' }, { label = ':older_woman:' }, { label = ':older_man:' },
    { label = ':person_with_blond_hair:' }, { label = ':man_with_gua_pi_mao:' }, { label = ':man_with_turban:' },
    { label = ':construction_worker:' }, { label = ':cop:' }, { label = ':angel:' },
    { label = ':princess:' }, { label = ':smiley_cat:' }, { label = ':smile_cat:' },
    { label = ':heart_eyes_cat:' }, { label = ':kissing_cat:' }, { label = ':smirk_cat:' },
    { label = ':scream_cat:' }, { label = ':crying_cat_face:' }, { label = ':joy_cat:' },
    { label = ':pouting_cat:' }, { label = ':japanese_ogre:' }, { label = ':japanese_goblin:' },
    { label = ':see_no_evil:' }, { label = ':hear_no_evil:' }, { label = ':speak_no_evil:' },
    { label = ':guardsman:' }, { label = ':skull:' }, { label = ':feet:' },
    { label = ':lips:' }, { label = ':kiss:' }, { label = ':droplet:' },
    { label = ':ear:' }, { label = ':eyes:' }, { label = ':nose:' },
    { label = ':tongue:' }, { label = ':love_letter:' }, { label = ':bust_in_silhouette:' },
    { label = ':busts_in_silhouette:' }, { label = ':speech_balloon:' }, { label = ':thought_balloon:' },
    { label = ':feelsgood:' }, { label = ':finnadie:' }, { label = ':goberserk:' },
    { label = ':godmode:' }, { label = ':hurtrealbad:' }, { label = ':rage1:' },
    { label = ':rage2:' }, { label = ':rage3:' }, { label = ':rage4:' },
    { label = ':suspect:' }, { label = ':trollface:' },
    { label = ':sunny:' }, { label = ':umbrella:' }, { label = ':cloud:' },
    { label = ':snowflake:' }, { label = ':snowman:' }, { label = ':zap:' },
    { label = ':cyclone:' }, { label = ':foggy:' }, { label = ':ocean:' },
    { label = ':cat:' }, { label = ':dog:' }, { label = ':mouse:' },
    { label = ':hamster:' }, { label = ':rabbit:' }, { label = ':wolf:' },
    { label = ':frog:' }, { label = ':tiger:' }, { label = ':koala:' },
    { label = ':bear:' }, { label = ':pig:' }, { label = ':pig_nose:' },
    { label = ':cow:' }, { label = ':boar:' }, { label = ':monkey_face:' },
    { label = ':monkey:' }, { label = ':horse:' }, { label = ':racehorse:' },
    { label = ':camel:' }, { label = ':sheep:' }, { label = ':elephant:' },
    { label = ':panda_face:' }, { label = ':snake:' }, { label = ':bird:' },
    { label = ':baby_chick:' }, { label = ':hatched_chick:' }, { label = ':hatching_chick:' },
    { label = ':chicken:' }, { label = ':penguin:' }, { label = ':turtle:' },
    { label = ':bug:' }, { label = ':honeybee:' }, { label = ':ant:' },
    { label = ':beetle:' }, { label = ':snail:' }, { label = ':octopus:' },
    { label = ':tropical_fish:' }, { label = ':fish:' }, { label = ':whale:' },
    { label = ':whale2:' }, { label = ':dolphin:' }, { label = ':cow2:' },
    { label = ':ram:' }, { label = ':rat:' }, { label = ':water_buffalo:' },
    { label = ':tiger2:' }, { label = ':rabbit2:' }, { label = ':dragon:' },
    { label = ':goat:' }, { label = ':rooster:' }, { label = ':dog2:' },
    { label = ':pig2:' }, { label = ':mouse2:' }, { label = ':ox:' },
    { label = ':dragon_face:' }, { label = ':blowfish:' }, { label = ':crocodile:' },
    { label = ':dromedary_camel:' }, { label = ':leopard:' }, { label = ':cat2:' },
    { label = ':poodle:' }, { label = ':paw_prints:' }, { label = ':bouquet:' },
    { label = ':cherry_blossom:' }, { label = ':tulip:' }, { label = ':four_leaf_clover:' },
    { label = ':rose:' }, { label = ':sunflower:' }, { label = ':hibiscus:' },
    { label = ':maple_leaf:' }, { label = ':leaves:' }, { label = ':fallen_leaf:' },
    { label = ':herb:' }, { label = ':mushroom:' }, { label = ':cactus:' },
    { label = ':palm_tree:' }, { label = ':evergreen_tree:' }, { label = ':deciduous_tree:' },
    { label = ':chestnut:' }, { label = ':seedling:' }, { label = ':blossom:' },
    { label = ':ear_of_rice:' }, { label = ':shell:' }, { label = ':globe_with_meridians:' },
    { label = ':sun_with_face:' }, { label = ':full_moon_with_face:' }, { label = ':new_moon_with_face:' },
    { label = ':new_moon:' }, { label = ':waxing_crescent_moon:' }, { label = ':first_quarter_moon:' },
    { label = ':waxing_gibbous_moon:' }, { label = ':full_moon:' }, { label = ':waning_gibbous_moon:' },
    { label = ':last_quarter_moon:' }, { label = ':waning_crescent_moon:' }, { label = ':last_quarter_moon_with_face:' },
    { label = ':first_quarter_moon_with_face:' }, { label = ':moon:' }, { label = ':earth_africa:' },
    { label = ':earth_americas:' }, { label = ':earth_asia:' }, { label = ':volcano:' },
    { label = ':milky_way:' }, { label = ':partly_sunny:' }, { label = ':octocat:' },
    { label = ':squirrel:' },

    { label = ':bamboo:' }, { label = ':gift_heart:' }, { label = ':dolls:' },
    { label = ':school_satchel:' }, { label = ':mortar_board:' }, { label = ':flags:' },
    { label = ':fireworks:' }, { label = ':sparkler:' }, { label = ':wind_chime:' },
    { label = ':rice_scene:' }, { label = ':jack_o_lantern:' }, { label = ':ghost:' },
    { label = ':santa:' }, { label = ':christmas_tree:' }, { label = ':gift:' },
    { label = ':bell:' }, { label = ':no_bell:' }, { label = ':tanabata_tree:' },
    { label = ':tada:' }, { label = ':confetti_ball:' }, { label = ':balloon:' },
    { label = ':crystal_ball:' }, { label = ':cd:' }, { label = ':dvd:' },
    { label = ':floppy_disk:' }, { label = ':camera:' }, { label = ':video_camera:' },
    { label = ':movie_camera:' }, { label = ':computer:' }, { label = ':tv:' },
    { label = ':iphone:' }, { label = ':phone:' }, { label = ':telephone:' },
    { label = ':telephone_receiver:' }, { label = ':pager:' }, { label = ':fax:' },
    { label = ':minidisc:' }, { label = ':vhs:' }, { label = ':sound:' },
    { label = ':speaker:' }, { label = ':mute:' }, { label = ':loudspeaker:' },
    { label = ':mega:' }, { label = ':hourglass:' }, { label = ':hourglass_flowing_sand:' },
    { label = ':alarm_clock:' }, { label = ':watch:' }, { label = ':radio:' },
    { label = ':satellite:' }, { label = ':loop:' }, { label = ':mag:' },
    { label = ':mag_right:' }, { label = ':unlock:' }, { label = ':lock:' },
    { label = ':lock_with_ink_pen:' }, { label = ':closed_lock_with_key:' }, { label = ':key:' },
    { label = ':bulb:' }, { label = ':flashlight:' }, { label = ':high_brightness:' },
    { label = ':low_brightness:' }, { label = ':electric_plug:' }, { label = ':battery:' },
    { label = ':calling:' }, { label = ':email:' }, { label = ':mailbox:' },
    { label = ':postbox:' }, { label = ':bath:' }, { label = ':bathtub:' },
    { label = ':shower:' }, { label = ':toilet:' }, { label = ':wrench:' },
    { label = ':nut_and_bolt:' }, { label = ':hammer:' }, { label = ':seat:' },
    { label = ':moneybag:' }, { label = ':yen:' }, { label = ':dollar:' },
    { label = ':pound:' }, { label = ':euro:' }, { label = ':credit_card:' },
    { label = ':money_with_wings:' }, { label = ':e-mail:' }, { label = ':inbox_tray:' },
    { label = ':outbox_tray:' }, { label = ':envelope:' }, { label = ':incoming_envelope:' },
    { label = ':postal_horn:' }, { label = ':mailbox_closed:' }, { label = ':mailbox_with_mail:' },
    { label = ':mailbox_with_no_mail:' }, { label = ':door:' }, { label = ':smoking:' },
    { label = ':bomb:' }, { label = ':gun:' }, { label = ':hocho:' },
    { label = ':pill:' }, { label = ':syringe:' }, { label = ':page_facing_up:' },
    { label = ':page_with_curl:' }, { label = ':bookmark_tabs:' }, { label = ':bar_chart:' },
    { label = ':chart_with_upwards_trend:' }, { label = ':chart_with_downwards_trend:' }, { label = ':scroll:' },
    { label = ':clipboard:' }, { label = ':calendar:' }, { label = ':date:' },
    { label = ':card_index:' }, { label = ':file_folder:' }, { label = ':open_file_folder:' },
    { label = ':scissors:' }, { label = ':pushpin:' }, { label = ':paperclip:' },
    { label = ':black_nib:' }, { label = ':pencil2:' }, { label = ':straight_ruler:' },
    { label = ':triangular_ruler:' }, { label = ':closed_book:' }, { label = ':green_book:' },
    { label = ':blue_book:' }, { label = ':orange_book:' }, { label = ':notebook:' },
    { label = ':notebook_with_decorative_cover:' }, { label = ':ledger:' }, { label = ':books:' },
    { label = ':bookmark:' }, { label = ':name_badge:' }, { label = ':microscope:' },
    { label = ':telescope:' }, { label = ':newspaper:' }, { label = ':football:' },
    { label = ':basketball:' }, { label = ':soccer:' }, { label = ':baseball:' },
    { label = ':tennis:' }, { label = ':8ball:' }, { label = ':rugby_football:' },
    { label = ':bowling:' }, { label = ':golf:' }, { label = ':mountain_bicyclist:' },
    { label = ':bicyclist:' }, { label = ':horse_racing:' }, { label = ':snowboarder:' },
    { label = ':swimmer:' }, { label = ':surfer:' }, { label = ':ski:' },
    { label = ':spades:' }, { label = ':hearts:' }, { label = ':clubs:' },
    { label = ':diamonds:' }, { label = ':gem:' }, { label = ':ring:' },
    { label = ':trophy:' }, { label = ':musical_score:' }, { label = ':musical_keyboard:' },
    { label = ':violin:' }, { label = ':space_invader:' }, { label = ':video_game:' },
    { label = ':black_joker:' }, { label = ':flower_playing_cards:' }, { label = ':game_die:' },
    { label = ':dart:' }, { label = ':mahjong:' }, { label = ':clapper:' },
    { label = ':memo:' }, { label = ':pencil:' }, { label = ':book:' },
    { label = ':art:' }, { label = ':microphone:' }, { label = ':headphones:' },
    { label = ':trumpet:' }, { label = ':saxophone:' }, { label = ':guitar:' },
    { label = ':shoe:' }, { label = ':sandal:' }, { label = ':high_heel:' },
    { label = ':lipstick:' }, { label = ':boot:' }, { label = ':shirt:' },
    { label = ':tshirt:' }, { label = ':necktie:' }, { label = ':womans_clothes:' },
    { label = ':dress:' }, { label = ':running_shirt_with_sash:' }, { label = ':jeans:' },
    { label = ':kimono:' }, { label = ':bikini:' }, { label = ':ribbon:' },
    { label = ':tophat:' }, { label = ':crown:' }, { label = ':womans_hat:' },
    { label = ':mans_shoe:' }, { label = ':closed_umbrella:' }, { label = ':briefcase:' },
    { label = ':handbag:' }, { label = ':pouch:' }, { label = ':purse:' },
    { label = ':eyeglasses:' }, { label = ':fishing_pole_and_fish:' }, { label = ':coffee:' },
    { label = ':tea:' }, { label = ':sake:' }, { label = ':baby_bottle:' },
    { label = ':beer:' }, { label = ':beers:' }, { label = ':cocktail:' },
    { label = ':tropical_drink:' }, { label = ':wine_glass:' }, { label = ':fork_and_knife:' },
    { label = ':pizza:' }, { label = ':hamburger:' }, { label = ':fries:' },
    { label = ':poultry_leg:' }, { label = ':meat_on_bone:' }, { label = ':spaghetti:' },
    { label = ':curry:' }, { label = ':fried_shrimp:' }, { label = ':bento:' },
    { label = ':sushi:' }, { label = ':fish_cake:' }, { label = ':rice_ball:' },
    { label = ':rice_cracker:' }, { label = ':rice:' }, { label = ':ramen:' },
    { label = ':stew:' }, { label = ':oden:' }, { label = ':dango:' },
    { label = ':egg:' }, { label = ':bread:' }, { label = ':doughnut:' },
    { label = ':custard:' }, { label = ':icecream:' }, { label = ':ice_cream:' },
    { label = ':shaved_ice:' }, { label = ':birthday:' }, { label = ':cake:' },
    { label = ':cookie:' }, { label = ':chocolate_bar:' }, { label = ':candy:' },
    { label = ':lollipop:' }, { label = ':honey_pot:' }, { label = ':apple:' },
    { label = ':green_apple:' }, { label = ':tangerine:' }, { label = ':lemon:' },
    { label = ':cherries:' }, { label = ':grapes:' }, { label = ':watermelon:' },
    { label = ':strawberry:' }, { label = ':peach:' }, { label = ':melon:' },
    { label = ':banana:' }, { label = ':pear:' }, { label = ':pineapple:' },
    { label = ':sweet_potato:' }, { label = ':eggplant:' }, { label = ':tomato:' },
    { label = ':corn:' },
    { label = ':house:' }, { label = ':house_with_garden:' }, { label = ':school:' },
    { label = ':office:' }, { label = ':post_office:' }, { label = ':hospital:' },
    { label = ':bank:' }, { label = ':convenience_store:' }, { label = ':love_hotel:' },
    { label = ':hotel:' }, { label = ':wedding:' }, { label = ':church:' },
    { label = ':department_store:' }, { label = ':european_post_office:' }, { label = ':city_sunrise:' },
    { label = ':city_sunset:' }, { label = ':japanese_castle:' }, { label = ':european_castle:' },
    { label = ':tent:' }, { label = ':factory:' }, { label = ':tokyo_tower:' },
    { label = ':japan:' }, { label = ':mount_fuji:' }, { label = ':sunrise_over_mountains:' },
    { label = ':sunrise:' }, { label = ':stars:' }, { label = ':statue_of_liberty:' },
    { label = ':bridge_at_night:' }, { label = ':carousel_horse:' }, { label = ':rainbow:' },
    { label = ':ferris_wheel:' }, { label = ':fountain:' }, { label = ':roller_coaster:' },
    { label = ':ship:' }, { label = ':speedboat:' }, { label = ':boat:' },
    { label = ':sailboat:' }, { label = ':rowboat:' }, { label = ':anchor:' },
    { label = ':rocket:' }, { label = ':airplane:' }, { label = ':helicopter:' },
    { label = ':steam_locomotive:' }, { label = ':tram:' }, { label = ':mountain_railway:' },
    { label = ':bike:' }, { label = ':aerial_tramway:' }, { label = ':suspension_railway:' },
    { label = ':mountain_cableway:' }, { label = ':tractor:' }, { label = ':blue_car:' },
    { label = ':oncoming_automobile:' }, { label = ':car:' }, { label = ':red_car:' },
    { label = ':taxi:' }, { label = ':oncoming_taxi:' }, { label = ':articulated_lorry:' },
    { label = ':bus:' }, { label = ':oncoming_bus:' }, { label = ':rotating_light:' },
    { label = ':police_car:' }, { label = ':oncoming_police_car:' }, { label = ':fire_engine:' },
    { label = ':ambulance:' }, { label = ':minibus:' }, { label = ':truck:' },
    { label = ':train:' }, { label = ':station:' }, { label = ':train2:' },
    { label = ':bullettrain_front:' }, { label = ':bullettrain_side:' }, { label = ':light_rail:' },
    { label = ':monorail:' }, { label = ':railway_car:' }, { label = ':trolleybus:' },
    { label = ':ticket:' }, { label = ':fuelpump:' }, { label = ':vertical_traffic_light:' },
    { label = ':traffic_light:' }, { label = ':warning:' }, { label = ':construction:' },
    { label = ':beginner:' }, { label = ':atm:' }, { label = ':slot_machine:' },
    { label = ':busstop:' }, { label = ':barber:' }, { label = ':hotsprings:' },
    { label = ':checkered_flag:' }, { label = ':crossed_flags:' }, { label = ':izakaya_lantern:' },
    { label = ':moyai:' }, { label = ':circus_tent:' }, { label = ':performing_arts:' },
    { label = ':round_pushpin:' }, { label = ':triangular_flag_on_post:' }, { label = ':jp:' },
    { label = ':kr:' }, { label = ':cn:' }, { label = ':us:' },
    { label = ':fr:' }, { label = ':es:' }, { label = ':it:' },
    { label = ':ru:' }, { label = ':gb:' }, { label = ':uk:' },
    { label = ':de:' },
    { label = ':one:' }, { label = ':two:' }, { label = ':three:' },
    { label = ':four:' }, { label = ':five:' }, { label = ':six:' },
    { label = ':seven:' }, { label = ':eight:' }, { label = ':nine:' },
    { label = ':keycap_ten:' }, { label = ':1234:' }, { label = ':zero:' },
    { label = ':hash:' }, { label = ':symbols:' }, { label = ':arrow_backward:' },
    { label = ':arrow_down:' }, { label = ':arrow_forward:' }, { label = ':arrow_left:' },
    { label = ':capital_abcd:' }, { label = ':abcd:' }, { label = ':abc:' },
    { label = ':arrow_lower_left:' }, { label = ':arrow_lower_right:' }, { label = ':arrow_right:' },
    { label = ':arrow_up:' }, { label = ':arrow_upper_left:' }, { label = ':arrow_upper_right:' },
    { label = ':arrow_double_down:' }, { label = ':arrow_double_up:' }, { label = ':arrow_down_small:' },
    { label = ':arrow_heading_down:' }, { label = ':arrow_heading_up:' }, { label = ':leftwards_arrow_with_hook:' },
    { label = ':arrow_right_hook:' }, { label = ':left_right_arrow:' }, { label = ':arrow_up_down:' },
    { label = ':arrow_up_small:' }, { label = ':arrows_clockwise:' }, { label = ':arrows_counterclockwise:' },
    { label = ':rewind:' }, { label = ':fast_forward:' }, { label = ':information_source:' },
    { label = ':ok:' }, { label = ':twisted_rightwards_arrows:' }, { label = ':repeat:' },
    { label = ':repeat_one:' }, { label = ':new:' }, { label = ':top:' },
    { label = ':up:' }, { label = ':cool:' }, { label = ':free:' },
    { label = ':ng:' }, { label = ':cinema:' }, { label = ':koko:' },
    { label = ':signal_strength:' }, { label = ':u5272:' }, { label = ':u5408:' },
    { label = ':u55b6:' }, { label = ':u6307:' }, { label = ':u6708:' },
    { label = ':u6709:' }, { label = ':u6e80:' }, { label = ':u7121:' },
    { label = ':u7533:' }, { label = ':u7a7a:' }, { label = ':u7981:' },
    { label = ':sa:' }, { label = ':restroom:' }, { label = ':mens:' },
    { label = ':womens:' }, { label = ':baby_symbol:' }, { label = ':no_smoking:' },
    { label = ':parking:' }, { label = ':wheelchair:' }, { label = ':metro:' },
    { label = ':baggage_claim:' }, { label = ':accept:' }, { label = ':wc:' },
    { label = ':potable_water:' }, { label = ':put_litter_in_its_place:' }, { label = ':secret:' },
    { label = ':congratulations:' }, { label = ':m:' }, { label = ':passport_control:' },
    { label = ':left_luggage:' }, { label = ':customs:' }, { label = ':ideograph_advantage:' },
    { label = ':cl:' }, { label = ':sos:' }, { label = ':id:' },
    { label = ':no_entry_sign:' }, { label = ':underage:' }, { label = ':no_mobile_phones:' },
    { label = ':do_not_litter:' }, { label = ':non-potable_water:' }, { label = ':no_bicycles:' },
    { label = ':no_pedestrians:' }, { label = ':children_crossing:' }, { label = ':no_entry:' },
    { label = ':eight_spoked_asterisk:' }, { label = ':eight_pointed_black_star:' }, { label = ':heart_decoration:' },
    { label = ':vs:' }, { label = ':vibration_mode:' }, { label = ':mobile_phone_off:' },
    { label = ':chart:' }, { label = ':currency_exchange:' }, { label = ':aries:' },
    { label = ':taurus:' }, { label = ':gemini:' }, { label = ':cancer:' },
    { label = ':leo:' }, { label = ':virgo:' }, { label = ':libra:' },
    { label = ':scorpius:' }, { label = ':sagittarius:' }, { label = ':capricorn:' },
    { label = ':aquarius:' }, { label = ':pisces:' }, { label = ':ophiuchus:' },
    { label = ':six_pointed_star:' }, { label = ':negative_squared_cross_mark:' }, { label = ':a:' },
    { label = ':b:' }, { label = ':ab:' }, { label = ':o2:' },
    { label = ':diamond_shape_with_a_dot_inside:' }, { label = ':recycle:' }, { label = ':end:' },
    { label = ':on:' }, { label = ':soon:' }, { label = ':clock1:' },
    { label = ':clock130:' }, { label = ':clock10:' }, { label = ':clock1030:' },
    { label = ':clock11:' }, { label = ':clock1130:' }, { label = ':clock12:' },
    { label = ':clock1230:' }, { label = ':clock2:' }, { label = ':clock230:' },
    { label = ':clock3:' }, { label = ':clock330:' }, { label = ':clock4:' },
    { label = ':clock430:' }, { label = ':clock5:' }, { label = ':clock530:' },
    { label = ':clock6:' }, { label = ':clock630:' }, { label = ':clock7:' },
    { label = ':clock730:' }, { label = ':clock8:' }, { label = ':clock830:' },
    { label = ':clock9:' }, { label = ':clock930:' }, { label = ':heavy_dollar_sign:' },
    { label = ':copyright:' }, { label = ':registered:' }, { label = ':tm:' },
    { label = ':x:' }, { label = ':heavy_exclamation_mark:' }, { label = ':bangbang:' },
    { label = ':interrobang:' }, { label = ':o:' }, { label = ':heavy_multiplication_x:' },
    { label = ':heavy_plus_sign:' }, { label = ':heavy_minus_sign:' }, { label = ':heavy_division_sign:' },
    { label = ':white_flower:' }, { label = ':100:' }, { label = ':heavy_check_mark:' },
    { label = ':ballot_box_with_check:' }, { label = ':radio_button:' }, { label = ':link:' },
    { label = ':curly_loop:' }, { label = ':wavy_dash:' }, { label = ':part_alternation_mark:' },
    { label = ':trident:' }, { label = ':black_square:' }, { label = ':white_square:' },
    { label = ':white_check_mark:' }, { label = ':black_square_button:' }, { label = ':white_square_button:' },
    { label = ':black_circle:' }, { label = ':white_circle:' }, { label = ':red_circle:' },
    { label = ':large_blue_circle:' }, { label = ':large_blue_diamond:' }, { label = ':large_orange_diamond:' },
    { label = ':small_blue_diamond:' }, { label = ':small_orange_diamond:' }, { label = ':small_red_triangle:' },
    { label = ':small_red_triangle_down:' }, { label = ':shipit:' },
  })
end

---Resolve completion item (optional). This is called right before the completion is about to be displayed.
---Useful for setting the text shown in the documentation window (`completion_item.documentation`).
---@param completion_item lsp.CompletionItem
---@param callback fun(completion_item: lsp.CompletionItem|nil)
function source:resolve(completion_item, callback)
  callback(completion_item)
end

---Executed after the item was selected.
---@param completion_item lsp.CompletionItem
---@param callback fun(completion_item: lsp.CompletionItem|nil)
function source:execute(completion_item, callback)
  callback(completion_item)
end

---Register your source to nvim-cmp.
require('cmp').register_source(name, source)
